[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/updates"
  to = "/updates/1"
  status = 302

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200